[platformio]
default_envs = esp32-s3-devkitc-1
description = Lindblad Community Miner Firmware A

[env]
platform = espressif32@6.5.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DLINDBLAD_FIRMWARE_A
    -DFIRMWARE_VERSION=\"0.2.0\"
    -DFIRMWARE_TYPE=\"COMMUNITY_MINER\"
    -I include
    -I src
    -std=gnu++17

build_unflags =
    -std=gnu++11

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    tzapu/WiFiManager@^2.0.16
    knolleary/PubSubClient@^2.8

board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.partitions = huge_app.csv

build_flags =
    ${env.build_flags}
    -DARDUINO_ESP32S3_DEV
